name: Deploy Dockerized App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=${{ secrets.INSTANCE_ID }}" \
            --parameters 'commands=[
              "cd /home/ubuntu/ || git clone https://github.com/pravar1919/django-test django-test",
              "cd /home/ubuntu/django-test",
              "git pull origin main",
              "docker build -t django-test:latest .",
              "docker stop django-test || true",
              "docker rm django-test || true",
              "docker run -d --name django-test -p 80:8000 django-test:latest"
            ]' \
            --comment "Deploy from GitHub Actions" \
            --output text
